# Install library

In [1]:
import torch
import numpy as np

# Numpy vs Tensor

In [2]:
# Creating a 2 * 2 array
array=[[1,1],[3,4]]
array

[[1, 1], [3, 4]]

In [3]:
# Convert to numpy
np.array(array)

array([[1, 1],
       [3, 4]])

In [4]:
# convert to tensor array
torch.Tensor(array)

tensor([[1., 1.],
        [3., 4.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

# Variables

In [7]:
from torch.autograd import Variable

In [8]:
a= Variable(torch.ones(2,2), requires_grad = True)
b= Variable(torch.ones(2,2), requires_grad = True)

In [9]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
b

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [11]:
a+b

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [12]:
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [13]:
torch.mul(a,b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)

In [14]:
torch.sub(a,b)

tensor([[0., 0.],
        [0., 0.]], grad_fn=<SubBackward0>)

In [15]:
torch.div(a,b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<DivBackward0>)

# Gradients

In [16]:
x = Variable(torch.ones(2), requires_grad = True)
x

tensor([1., 1.], requires_grad=True)

In [17]:
print(x.size())
print(x.dtype)

torch.Size([2])
torch.float32


In [19]:
y = 5 *( x +1) **2

In [20]:
o = (1/2) *  (torch.sum(y))
o

tensor(20., grad_fn=<MulBackward0>)

In [21]:
print(o.size())
print(o.dtype)

torch.Size([])
torch.float32


In [24]:
# calculate gradient with respect to x, since x 
o.backward()

In [25]:
print(x.grad)

tensor([10., 10.])
